FROM alpine:3

LABEL author="Fauzan Andyka Ramadhani"
LABEL company="Gymbro" 
LABEL website="https://tribunkaltimwiki.tribunnews.com/2020/02/24/ini-daftar-tempat-fitness-di-hotel-balikpapan-beserta-harganya?page=all"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"